name = 'antifem-main-site'
main = "worker.js"
compatibility_date = "2025-08-07"

[assets]
directory = "docs"
binding = "ASSETS"

# Для привязки собственного домена вместо workers_dev укажите routes/zones, пример:
# routes = [
#   { pattern = "example.com/*", zone_name = "example.com" }
# ]
