backend:
  name: github
  repo: bozonx/antifem-site
  use_graphql: true
  site_domain: 5ab4c367-3592-4361-a4b8-ccd46514c967

# publish_mode: editorial_workflow
site_url: https://antifem-move.org
media_folder: src/public/media
public_folder: /media
# locale: ru
# media_library:
#   max_file_size: 512000
#   folder_support: true
slug:
  encoding: ascii
  clean_accents: true
i18n:
  structure: multiple_folders
  locales: [en, ru]
  default_locale: en
  enforce_required_non_default: false
  canonical_slug:
    # key: defaultLocaleVersion # default: translationKey
    value: "{{locale}}/{{slug}}" # default: {{slug}}
  # save_all_locales: false
collections:
  - name: doc
    label: Docs
    label_singular: Doc
    description: All the docs
    i18n: true
    folder: "src"
    # files: "src/{{locale}}/doc"
    path: "doc/{{slug}}"
    # path: "doc"
    # preview_path: "blog/{{year}}/{{month}}/{{slug}}"
    # slug: "doc-{{slug}}"
    create: true
    summary: "{{dirname}}/{{filename}} {{commit_date | date('yyyy-MM-dd')}} {{title}}"
    # sortable_fields:
    #   fields: ["commit_date", "title", "commit_author"]
    #   default:
    #     field: commit_date
    #     direction: Descending
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        preview: false
        i18n: true
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
        preview: false
        i18n: true
      - label: "Body"
        name: "body"
        widget: "markdown"
        modes: ["raw", "rich_text"]
        i18n: true
        show_raw: true
  - name: files
    label: "Files"
    i18n: true
    files:
      - name: sidebar
        label: Sidebar translation
        extension: yaml
        format: yaml
        file: "src/site/sidebar.{{locale}}.yaml"
        i18n: true
        fields:
          - name: "title"
            widget: "hidden"
            default: Sidebar
            i18n: duplicate
          - label: "Body"
            name: "body"
            widget: "text"
            # default_language: yaml
            i18n: true
      - name: site
        label: Site translations
        extension: yaml
        format: yaml
        file: "src/site/site.{{locale}}.yaml"
        i18n: true
        fields:
          - name: "title"
            widget: "hidden"
            default: Sidebar
            i18n: duplicate
          - label: "Body"
            name: "body"
            widget: "text"
            # default_language: yaml
            i18n: true
      - name: home
        label: Home page
        file: "src/{{locale}}/index.md"
        format: frontmatter
        i18n: true
        # widget: "text"
        fields:
          #   - label: "Title"
          #     name: "title"
          #     widget: "string"
          #     i18n: true
          #   - label: "Description"
          #     name: "description"
          #     widget: "text"
          #     required: false
          #     i18n: true
          - label: "Body"
            name: "body"
            widget: "text"
            i18n: true

  # - name: pages
  #   label: Pages
  #   label_singular: Page
  #   description: Site pages
  #   i18n: true
  #   # folder: "src/{{locale}}/page"
  #   folder: "src"
  #   # path: "page/{{slug}}"
  #   # path: "page"
  #   # preview_path: "blog/{{year}}/{{month}}/{{slug}}"
  #   create: false
  #   delete: false
  #   summary: "{{dirname}}/{{filename}} {{commit_date | date('yyyy-MM-dd')}} {{title}}"
  #   fields:
  #     - label: "Title"
  #       name: "title"
  #       widget: "string"
  #       i18n: true
  #     - label: "Description"
  #       name: "description"
  #       widget: "text"
  #       required: false
  #       i18n: true
  #     - label: "Body"
  #       name: "body"
  #       widget: "markdown"
  #       i18n: true
  #       show_raw: true
  # - name: sidebar1
  #   label: "Sidebar"
  #   i18n:
  #     structure: multiple_files
  #   delete: false
  #   extension: yaml
  #   format: yaml
  #   folder: "src/.vitepress/locales/menu"
  #   slug: "{{slug}}.{{locale}}"
  #   fields:
  #     - label: "Title"
  #       name: "title"
  #       widget: "string"
  #     - label: "Body"
  #       name: "body"
  #       widget: "text"
  #       # default_language: yaml
  #       i18n: true
